name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:ci

    - name: Build application
      run: npm run build

    - name: Package for distribution
      run: npm run dist:win-msi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-troubleshooting-companion
        path: release/

  release:
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-troubleshooting-companion

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.exe
          *.msi
          *.blockmap
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}